### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by EwanCroft** [EwanCroft/Snek#1]
As the title implies, this needs a licence. I am not sure what licence to use though.

**Comment by CosmicRaichu** [comment]
I personally like the GPLv3, but that's just my personal preference. This site may be useful for making a decision.

https://choosealicense.com/

**Comment by EwanCroft** [comment]
Oh yeah, that could help. Totally forgot about that site lol.

**Comment by EwanCroft** [comment]
I'll use it, fits the purpose of this project.
